export default {
  CreateUser: "/create_user",
  getUsers: "/get_admin_user",
  contactUs: "/contact_us",
  tutorial: "get_tutorial",
  addWard: "create_ward",
  updateProfile: "update_profile",
  getCreateAuditData: "create_admin_audit",
  getWards: "get_ward",
  getUserWards: "get_ward_user",
  createAudit: "admin_audit",
  forgot_password: "forgot_password",
  forgot_password_code: "forgot_password_code",
  new_password: "new_password",
  get_audit_site: "get_audit_site",
  perform_audit: "perform_audit",
  user_audit: "user_audit",
  superuser_audit_result: "get_admin_user_audit",
  user_audit_result: "user_audit_result",
};
